### ISSUE TITLE
Resolver el bug del filtrado de eventos por ubicación en la homepage

### ISSUE THREAD

**Issue by fimbres** [fimbres/friendly-sport#44]
En el servidor dónde está alojado el proyecto no se muestra ningún evento, sin importar si ya creaste uno justo en tu ubicación.

Lo que creo es que pueda deberse a que se calcula la ubicación del usuario por medio de la IP, intenta cambiarlo a acceder a la ubicación por medio de JavaScript como en la página de crear evento, pero puedes resolverlo cómo prefieras.

**Comment by patinoAlexis** [comment]
Con el nuevo pull request hecho, este issue termina cerrado.
