### ISSUE TITLE
El usuario deberia poder cancelar/borrar evento

### ISSUE THREAD

**Issue by pruebaer** [fimbres/friendly-sport#5]

**Comment by pruebaer** [comment]
El usuario deberia poder cancelar/borrar evento

**Comment by fimbres** [comment]
Puedes copiar y pegar el formulario de crear evento para ahorrarte mucho trabajo, sólo deshabilita todos los input para que la información no pueda ser editable, cambia las cosas para que se parezca a Figma, utiliza el stored procedure para eliminar el evento seleccionado y muestra los cuadros de text que están en Figma.
